#! /usr/bin/env python
# -*- coding: utf-8 -*-

import portfolio

CONFIGS = [
    [
        1,
        [
            "--heuristic",
            "hGoalCount=goalcount(cost_type=2)",
            "--heuristic",
            "hFF=ff(cost_type=0)",
            "--search",
            "lazy(alt([single(sum([g(),weight(hFF,10)])),single(sum([g(),weight(hFF,10)]),pref_only=true),single(sum([g(),weight(hGoalCount,10)])),single(sum([g(),weight(hGoalCount,10)]),pref_only=true)],boost=2000),preferred=[hFF,hGoalCount],reopen_closed=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        142,
        [
            "--landmarks",
            "lmg=lm_rhw(reasonable_orders=false,only_causal_landmarks=false,disjunctive_landmarks=false,conjunctive_landmarks=true,no_orders=false,lm_cost_type=2,cost_type=1)",
            "--heuristic",
            "hLM,hFF=lm_ff_syn(lmg,admissible=false)",
            "--heuristic",
            "hBlind=blind()",
            "--search",
            "lazy(alt([single(sum([g(),weight(hBlind,2)])),single(sum([g(),weight(hBlind,2)]),pref_only=true),single(sum([g(),weight(hLM,2)])),single(sum([g(),weight(hLM,2)]),pref_only=true),single(sum([g(),weight(hFF,2)])),single(sum([g(),weight(hFF,2)]),pref_only=true)],boost=4419),preferred=[hLM],reopen_closed=true,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        60,
        [
            "--heuristic",
            "hFF=ff(cost_type=1)",
            "--search",
            "lazy(alt([single(sum([g(),weight(hFF,10)])),single(sum([g(),weight(hFF,10)]),pref_only=true)],boost=2000),preferred=[hFF],reopen_closed=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        121,
        [
            "--heuristic",
            "hAdd=add(cost_type=2)",
            "--heuristic",
            "hFF=ff(cost_type=0)",
            "--search",
            "lazy(alt([tiebreaking([sum([weight(g(),4),weight(hFF,5)]),hFF]),tiebreaking([sum([weight(g(),4),weight(hFF,5)]),hFF],pref_only=true),tiebreaking([sum([weight(g(),4),weight(hAdd,5)]),hAdd]),tiebreaking([sum([weight(g(),4),weight(hAdd,5)]),hAdd],pref_only=true)],boost=2537),preferred=[hFF,hAdd],reopen_closed=true,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        403,
        [
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hAdd=add(cost_type=0)",
            "--heuristic",
            "hCg=cg(cost_type=1)",
            "--heuristic",
            "hHMax=hmax()",
            "--search",
            "eager(alt([tiebreaking([sum([g(),weight(hBlind,7)]),hBlind]),tiebreaking([sum([g(),weight(hHMax,7)]),hHMax]),tiebreaking([sum([g(),weight(hAdd,7)]),hAdd]),tiebreaking([sum([g(),weight(hCg,7)]),hCg])],boost=2142),preferred=[],reopen_closed=true,pathmax=true,lookahead=false,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        1,
        [
            "--heuristic",
            "hCea=cea(cost_type=1)",
            "--heuristic",
            "hFF=ff(cost_type=2)",
            "--heuristic",
            "hBlind=blind()",
            "--search",
            "eager(alt([single(sum([g(),weight(hBlind,10)])),single(sum([g(),weight(hBlind,10)]),pref_only=true),single(sum([g(),weight(hFF,10)])),single(sum([g(),weight(hFF,10)]),pref_only=true),single(sum([g(),weight(hCea,10)])),single(sum([g(),weight(hCea,10)]),pref_only=true)],boost=536),preferred=[hFF],reopen_closed=false,pathmax=false,lookahead=true,la_greedy=false,la_repair=true,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        563,
        [
            "--landmarks",
            "lmg=lm_zg(reasonable_orders=true,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=true,cost_type=1)",
            "--heuristic",
            "hHMax=hmax()",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=false,pref=true,cost_type=1)",
            "--heuristic",
            "hCea=cea(cost_type=2)",
            "--heuristic",
            "hFF=ff(cost_type=1)",
            "--heuristic",
            "hCg=cg(cost_type=2)",
            "--search",
            "lazy(alt([tiebreaking([sum([g(),weight(hFF,10)]),hFF]),tiebreaking([sum([g(),weight(hFF,10)]),hFF],pref_only=true),tiebreaking([sum([g(),weight(hLM,10)]),hLM]),tiebreaking([sum([g(),weight(hLM,10)]),hLM],pref_only=true),tiebreaking([sum([g(),weight(hHMax,10)]),hHMax]),tiebreaking([sum([g(),weight(hHMax,10)]),hHMax],pref_only=true),tiebreaking([sum([g(),weight(hCg,10)]),hCg]),tiebreaking([sum([g(),weight(hCg,10)]),hCg],pref_only=true),tiebreaking([sum([g(),weight(hCea,10)]),hCea]),tiebreaking([sum([g(),weight(hCea,10)]),hCea],pref_only=true)],boost=4817),preferred=[hFF,hCg],reopen_closed=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        1,
        [
            "--landmarks",
            "lmg=lm_rhw(reasonable_orders=false,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=true,cost_type=1)",
            "--heuristic",
            "hHMax=hmax()",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=false,pref=false,cost_type=1)",
            "--heuristic",
            "hAdd=add(cost_type=0)",
            "--search",
            "lazy(alt([tiebreaking([sum([weight(g(),2),weight(hLM,3)]),hLM]),tiebreaking([sum([weight(g(),2),weight(hHMax,3)]),hHMax]),tiebreaking([sum([weight(g(),2),weight(hAdd,3)]),hAdd])],boost=3002),preferred=[],reopen_closed=true,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        62,
        [
            "--landmarks",
            "lmg=lm_zg(reasonable_orders=false,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=true,cost_type=0)",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=true,pref=false,cost_type=0)",
            "--search",
            "eager(single(sum([g(),weight(hLM,3)])),preferred=[],reopen_closed=true,pathmax=false,lookahead=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        50,
        [
            "--landmarks",
            "lmg=lm_rhw(reasonable_orders=true,only_causal_landmarks=true,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=false,cost_type=2)",
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hAdd=add(cost_type=0)",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=false,pref=true,cost_type=2)",
            "--heuristic",
            "hFF=ff(cost_type=0)",
            "--search",
            "lazy(alt([single(sum([weight(g(),2),weight(hBlind,3)])),single(sum([weight(g(),2),weight(hBlind,3)]),pref_only=true),single(sum([weight(g(),2),weight(hFF,3)])),single(sum([weight(g(),2),weight(hFF,3)]),pref_only=true),single(sum([weight(g(),2),weight(hLM,3)])),single(sum([weight(g(),2),weight(hLM,3)]),pref_only=true),single(sum([weight(g(),2),weight(hAdd,3)])),single(sum([weight(g(),2),weight(hAdd,3)]),pref_only=true)],boost=2474),preferred=[hAdd],reopen_closed=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        188,
        [
            "--heuristic",
            "hCg=cg(cost_type=1)",
            "--heuristic",
            "hHMax=hmax()",
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hGoalCount=goalcount(cost_type=1)",
            "--search",
            "eager(alt([tiebreaking([sum([weight(g(),4),weight(hBlind,5)]),hBlind]),tiebreaking([sum([weight(g(),4),weight(hHMax,5)]),hHMax]),tiebreaking([sum([weight(g(),4),weight(hCg,5)]),hCg]),tiebreaking([sum([weight(g(),4),weight(hGoalCount,5)]),hGoalCount])],boost=1284),preferred=[],reopen_closed=false,pathmax=true,lookahead=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        2,
        [
            "--landmarks",
            "lmg=lm_exhaust(reasonable_orders=false,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=false,lm_cost_type=1,cost_type=0)",
            "--heuristic",
            "hGoalCount=goalcount(cost_type=2)",
            "--heuristic",
            "hLM,hFF=lm_ff_syn(lmg,admissible=false)",
            "--heuristic",
            "hBlind=blind()",
            "--search",
            "eager(alt([tiebreaking([sum([weight(g(),8),weight(hBlind,9)]),hBlind]),tiebreaking([sum([weight(g(),8),weight(hLM,9)]),hLM]),tiebreaking([sum([weight(g(),8),weight(hFF,9)]),hFF]),tiebreaking([sum([weight(g(),8),weight(hGoalCount,9)]),hGoalCount])],boost=2005),preferred=[],reopen_closed=true,pathmax=true,lookahead=false,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        78,
        [
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hFF=ff(cost_type=1)",
            "--search",
            "eager(alt([single(sum([g(),weight(hBlind,2)])),single(sum([g(),weight(hFF,2)]))],boost=4480),preferred=[],reopen_closed=true,pathmax=true,lookahead=true,la_greedy=true,la_repair=true,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        60,
        [
            "--heuristic",
            "hCea=cea(cost_type=1)",
            "--heuristic",
            "hFF=ff(cost_type=2)",
            "--heuristic",
            "hGoalCount=goalcount(cost_type=2)",
            "--heuristic",
            "hBlind=blind()",
            "--search",
            "lazy(alt([tiebreaking([sum([g(),weight(hBlind,10)]),hBlind]),tiebreaking([sum([g(),weight(hBlind,10)]),hBlind],pref_only=true),tiebreaking([sum([g(),weight(hFF,10)]),hFF]),tiebreaking([sum([g(),weight(hFF,10)]),hFF],pref_only=true),tiebreaking([sum([g(),weight(hCea,10)]),hCea]),tiebreaking([sum([g(),weight(hCea,10)]),hCea],pref_only=true),tiebreaking([sum([g(),weight(hGoalCount,10)]),hGoalCount]),tiebreaking([sum([g(),weight(hGoalCount,10)]),hGoalCount],pref_only=true)],boost=2222),preferred=[hCea,hGoalCount],reopen_closed=false,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        3,
        [
            "--heuristic",
            "hFF=ff(cost_type=2)",
            "--search",
            "lazy(alt([tiebreaking([sum([g(),hFF]),hFF]),tiebreaking([sum([g(),hFF]),hFF],pref_only=true)],boost=432),preferred=[hFF],reopen_closed=true,cost_type=1,bound=BOUND)"
        ]
    ],
    [
        50,
        [
            "--heuristic",
            "hGoalCount=goalcount(cost_type=1)",
            "--heuristic",
            "hFF=ff(cost_type=2)",
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hCg=cg(cost_type=0)",
            "--search",
            "lazy(alt([single(sum([weight(g(),2),weight(hBlind,3)])),single(sum([weight(g(),2),weight(hBlind,3)]),pref_only=true),single(sum([weight(g(),2),weight(hFF,3)])),single(sum([weight(g(),2),weight(hFF,3)]),pref_only=true),single(sum([weight(g(),2),weight(hCg,3)])),single(sum([weight(g(),2),weight(hCg,3)]),pref_only=true),single(sum([weight(g(),2),weight(hGoalCount,3)])),single(sum([weight(g(),2),weight(hGoalCount,3)]),pref_only=true)],boost=3662),preferred=[hFF],reopen_closed=true,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        14,
        [
            "--landmarks",
            "lmg=lm_zg(reasonable_orders=true,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=false,cost_type=1)",
            "--heuristic",
            "hCg=cg(cost_type=1)",
            "--heuristic",
            "hGoalCount=goalcount(cost_type=0)",
            "--heuristic",
            "hHMax=hmax()",
            "--heuristic",
            "hCea=cea(cost_type=0)",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=false,pref=true,cost_type=1)",
            "--search",
            "lazy(alt([single(sum([weight(g(),2),weight(hLM,3)])),single(sum([weight(g(),2),weight(hLM,3)]),pref_only=true),single(sum([weight(g(),2),weight(hHMax,3)])),single(sum([weight(g(),2),weight(hHMax,3)]),pref_only=true),single(sum([weight(g(),2),weight(hCg,3)])),single(sum([weight(g(),2),weight(hCg,3)]),pref_only=true),single(sum([weight(g(),2),weight(hCea,3)])),single(sum([weight(g(),2),weight(hCea,3)]),pref_only=true),single(sum([weight(g(),2),weight(hGoalCount,3)])),single(sum([weight(g(),2),weight(hGoalCount,3)]),pref_only=true)],boost=2508),preferred=[hCea,hGoalCount],reopen_closed=false,cost_type=0,bound=BOUND)"
        ]
    ],
    [
        1,
        [
            "--landmarks",
            "lmg=lm_exhaust(reasonable_orders=false,only_causal_landmarks=false,disjunctive_landmarks=true,conjunctive_landmarks=true,no_orders=false,cost_type=1)",
            "--heuristic",
            "hFF=ff(cost_type=2)",
            "--heuristic",
            "hHMax=hmax()",
            "--heuristic",
            "hBlind=blind()",
            "--heuristic",
            "hLM=lmcount(lmg,admissible=true,pref=false,cost_type=1)",
            "--search",
            "lazy(alt([single(sum([g(),weight(hBlind,3)])),single(sum([g(),weight(hBlind,3)]),pref_only=true),single(sum([g(),weight(hFF,3)])),single(sum([g(),weight(hFF,3)]),pref_only=true),single(sum([g(),weight(hLM,3)])),single(sum([g(),weight(hLM,3)]),pref_only=true),single(sum([g(),weight(hHMax,3)])),single(sum([g(),weight(hHMax,3)]),pref_only=true)],boost=3052),preferred=[hFF],reopen_closed=true,cost_type=0,bound=BOUND)"
        ]
    ]
]

if __name__ == '__main__':
    portfolio.run(CONFIGS, optimal=False)
